import * as esbuild from "esbuild";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

// Build configuration
const BUILD_DIR = "build";
const RELEASE_DIR = "release";

// Entry points configuration
const ENTRY_POINTS = [
  { name: "agent", entry: "agent.ts" },
];

// pkg target platforms configuration
const PKG_TARGETS = [
  "node20-macos-x64",
  "node20-macos-arm64",
  "node20-linux-x64",
  "node20-win-x64",
];

// Clean directory
function cleanDir(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true });
  }
  fs.mkdirSync(dir, { recursive: true });
}

// Build CommonJS bundle using esbuild
async function buildWithEsbuild() {
  console.log("📦 Building CommonJS bundle with esbuild...\n");

  cleanDir(BUILD_DIR);

  for (const { name, entry } of ENTRY_POINTS) {
    console.log(`  Building ${name}...`);

    await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      platform: "node",
      target: "node20",
      format: "cjs",
      outfile: `${BUILD_DIR}/${name}.cjs`,
      minify: false, // Keep readable for debugging
      sourcemap: false,
      // Exclude native modules that cannot be bundled
      external: [],
      // Handle __dirname and __filename
      define: {},
      // Allow dynamic require
      banner: {
        js: `
// Generated by esbuild - CommonJS bundle
const __importMetaUrl = require('url').pathToFileURL(__filename).href;
`,
      },
    });

    const stats = fs.statSync(`${BUILD_DIR}/${name}.cjs`);
    console.log(`  ✅ ${name}.cjs (${(stats.size / 1024).toFixed(1)} KB)`);
  }

  console.log("\n✅ esbuild build completed\n");
}

// Package executables using pkg
async function packageWithPkg() {
  console.log("🔧 Packaging executables with pkg...\n");

  cleanDir(RELEASE_DIR);

  for (const { name } of ENTRY_POINTS) {
    const inputFile = `${BUILD_DIR}/${name}.cjs`;

    for (const target of PKG_TARGETS) {
      const [, os, arch] = target.match(/node\d+-(\w+)-(\w+)/);
      const ext = os === "win" ? ".exe" : "";
      const outputName = `${name}-${os}-${arch}${ext}`;
      const outputPath = `${RELEASE_DIR}/${outputName}`;

      console.log(`  Packaging ${outputName}...`);

      try {
        execSync(
          `npx pkg ${inputFile} --target ${target} --output ${outputPath}`,
          {
            stdio: "pipe",
          }
        );

        const stats = fs.statSync(outputPath);
        console.log(
          `  ✅ ${outputName} (${(stats.size / 1024 / 1024).toFixed(1)} MB)`
        );
      } catch (error) {
        console.error(`  ❌ Failed to package ${outputName}:`, error.message);
      }
    }
  }

  console.log("\n✅ pkg packaging completed\n");
}

// Generate SHA256 checksums
function generateChecksums() {
  console.log("🔐 Generating SHA256 checksums...\n");

  const checksums = [];
  const files = fs.readdirSync(RELEASE_DIR);

  for (const file of files) {
    if (file === "checksums.txt") continue;

    const filePath = path.join(RELEASE_DIR, file);
    const hash = execSync(`shasum -a 256 "${filePath}"`).toString().trim();
    checksums.push(hash);
    console.log(`  ${hash.split("  ")[0].slice(0, 16)}... ${file}`);
  }

  fs.writeFileSync(`${RELEASE_DIR}/checksums.txt`, checksums.join("\n") + "\n");
  console.log(`\n✅ checksums.txt generated\n`);
}

// Display build results
function showResults() {
  console.log("═".repeat(60));
  console.log("📋 Build Results");
  console.log("═".repeat(60));

  const files = fs.readdirSync(RELEASE_DIR);
  for (const file of files) {
    const filePath = path.join(RELEASE_DIR, file);
    const stats = fs.statSync(filePath);
    const size =
      stats.size > 1024 * 1024
        ? `${(stats.size / 1024 / 1024).toFixed(1)} MB`
        : `${(stats.size / 1024).toFixed(1)} KB`;
    console.log(`  ${file.padEnd(35)} ${size}`);
  }

  console.log("═".repeat(60));
  console.log(`\n💡 Usage:`);
  console.log(`   macOS (Intel):  ./release/agent-macos-x64`);
  console.log(`   macOS (Apple):  ./release/agent-macos-arm64`);
  console.log(`   Linux:          ./release/agent-linux-x64`);
  console.log(`   Windows:        .\\release\\agent-win-x64.exe`);
  console.log("");
}

// Main function
async function main() {
  const args = process.argv.slice(2);
  const skipPkg = args.includes("--skip-pkg");

  console.log("");
  console.log("╔══════════════════════════════════════════════════════════════╗");
  console.log("║              🚀 Build Release Packages                        ║");
  console.log("╚══════════════════════════════════════════════════════════════╝");
  console.log("");

  try {
    // Step 1: esbuild build
    await buildWithEsbuild();

    if (!skipPkg) {
      // Step 2: pkg packaging
      await packageWithPkg();

      // Step 3: Generate checksums
      generateChecksums();

      // Display results
      showResults();
    } else {
      console.log("⏭️  Skipping pkg packaging (--skip-pkg)\n");
      console.log(`📁 CommonJS bundles generated in ${BUILD_DIR}/ directory`);
    }
  } catch (error) {
    console.error("\n❌ Build failed:", error);
    process.exit(1);
  }
}

main();
